-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 13:19:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE librarymanagementdb;
-- -----------------------------------------------------
-- Table `LibraryCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryCard` ;

CREATE TABLE IF NOT EXISTS `LibraryCard` (
  `LibraryCard` INT NOT NULL,
  `Expiry` DATE NULL,
  `Account_ID` INT NOT NULL,
  PRIMARY KEY (`LibraryCard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `User` INT NULL,
  `Role` INT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `LibraryCard_LibraryCard` INT NOT NULL,
  PRIMARY KEY (`ID`, `LibraryCard_LibraryCard`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Account_LibraryCard1_idx` (`LibraryCard_LibraryCard` ASC) VISIBLE,
  CONSTRAINT `fk_Account_LibraryCard1`
    FOREIGN KEY (`LibraryCard_LibraryCard`)
    REFERENCES `LibraryCard` (`LibraryCard`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeneralUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeneralUser` ;

CREATE TABLE IF NOT EXISTS `GeneralUser` (
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RegisteredUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RegisteredUsers` ;

CREATE TABLE IF NOT EXISTS `RegisteredUsers` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL,
  `Address` VARCHAR(100) NULL,
  `Account_ID1` INT NOT NULL,
  `GeneralUser_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`, `GeneralUser_Type`),
  INDEX `fk_RegisteredUsers_Account1_idx` (`Account_ID1` ASC) VISIBLE,
  INDEX `fk_RegisteredUsers_GeneralUser1_idx` (`GeneralUser_Type` ASC) VISIBLE,
  CONSTRAINT `fk_RegisteredUsers_Account1`
    FOREIGN KEY (`Account_ID1`)
    REFERENCES `Account` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RegisteredUsers_GeneralUser1`
    FOREIGN KEY (`GeneralUser_Type`)
    REFERENCES `GeneralUser` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `studentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Account_ID` INT NOT NULL,
  PRIMARY KEY (`studentID`),
  INDEX `fk_Student_Account1_idx` (`Account_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Account1`
    FOREIGN KEY (`Account_ID`)
    REFERENCES `Account` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faculty` ;

CREATE TABLE IF NOT EXISTS `Faculty` (
  `facultyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Account_ID` INT NOT NULL,
  PRIMARY KEY (`facultyID`),
  INDEX `fk_Faculty_Account1_idx` (`Account_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Faculty_Account1`
    FOREIGN KEY (`Account_ID`)
    REFERENCES `Account` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Catalog` ;

CREATE TABLE IF NOT EXISTS `Catalog` (
  `catalogID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`catalogID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultimediaContent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultimediaContent` ;

CREATE TABLE IF NOT EXISTS `MultimediaContent` (
  `multimediaContentID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`multimediaContentID`),
  CONSTRAINT `fk_MultimediaContent_Catalog1`
    FOREIGN KEY (`multimediaContentID`)
    REFERENCES `Catalog` (`catalogID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResearchPaper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResearchPaper` ;

CREATE TABLE IF NOT EXISTS `ResearchPaper` (
  `PMID` INT NOT NULL AUTO_INCREMENT,
  `Author` VARCHAR(45) NULL,
  `PublishedDate` DATE NULL,
  `Abstract` VARCHAR(255) NULL,
  `Publisher` VARCHAR(45) NULL,
  PRIMARY KEY (`PMID`),
  CONSTRAINT `PMID`
    FOREIGN KEY (`PMID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Videos` ;

CREATE TABLE IF NOT EXISTS `Videos` (
  `videoID` INT NOT NULL AUTO_INCREMENT,
  `Credits` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  `PublishedDate` DATE NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`videoID`),
  CONSTRAINT `VideoID`
    FOREIGN KEY (`videoID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Music` ;

CREATE TABLE IF NOT EXISTS `Music` (
  `musicID` INT NOT NULL AUTO_INCREMENT,
  `Artist` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  `PublishedDate` VARCHAR(45) NULL,
  `Producer` VARCHAR(45) NULL,
  `Language` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`musicID`),
  CONSTRAINT `MusicID`
    FOREIGN KEY (`musicID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eBooks` ;

CREATE TABLE IF NOT EXISTS `eBooks` (
  `ebookID` INT NOT NULL AUTO_INCREMENT,
  `Publishers` VARCHAR(45) NULL,
  `Author` VARCHAR(45) NULL,
  PRIMARY KEY (`ebookID`),
  CONSTRAINT `eBookID`
    FOREIGN KEY (`ebookID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Entries` ;

CREATE TABLE IF NOT EXISTS `Entries` (
  `entryID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`entryID`),
  CONSTRAINT `fk_Entries_Catalog1`
    FOREIGN KEY (`entryID`)
    REFERENCES `Catalog` (`catalogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Magazine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Magazine` ;

CREATE TABLE IF NOT EXISTS `Magazine` (
  `magazineID` INT NOT NULL AUTO_INCREMENT,
  `Publisher` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  `CallNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`magazineID`),
  CONSTRAINT `MagazineID`
    FOREIGN KEY (`magazineID`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Encyclopedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encyclopedia` ;

CREATE TABLE IF NOT EXISTS `Encyclopedia` (
  `encyclopediaID` INT NOT NULL AUTO_INCREMENT,
  `Publisher` VARCHAR(45) NULL,
  `PublishingDate` DATE NULL,
  `Description` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  `CallNumber` DOUBLE NULL,
  PRIMARY KEY (`encyclopediaID`),
  UNIQUE INDEX `CallNumber_UNIQUE` (`CallNumber` ASC) VISIBLE,
  CONSTRAINT `EncyclopediaID`
    FOREIGN KEY (`encyclopediaID`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thesaurus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Thesaurus` ;

CREATE TABLE IF NOT EXISTS `Thesaurus` (
  `thesaurusID` INT NOT NULL AUTO_INCREMENT,
  `CallNumber` DOUBLE NULL,
  `Publisher` VARCHAR(45) NULL,
  `Title` VARCHAR(45) NULL,
  PRIMARY KEY (`thesaurusID`),
  UNIQUE INDEX `CallNumber_UNIQUE` (`CallNumber` ASC) VISIBLE,
  CONSTRAINT `ThesaurusID`
    FOREIGN KEY (`thesaurusID`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `transactionID` INT NOT NULL,
  `PaymentDate` DATE NOT NULL,
  `Total` INT NOT NULL,
  `PaymentType` VARCHAR(45) NOT NULL,
  `RegisteredUsers_userID` INT NOT NULL,
  PRIMARY KEY (`transactionID`, `RegisteredUsers_userID`),
  UNIQUE INDEX `transactionID_UNIQUE` (`transactionID` ASC) VISIBLE,
  INDEX `fk_Payment_RegisteredUsers1_idx` (`RegisteredUsers_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_RegisteredUsers1`
    FOREIGN KEY (`RegisteredUsers_userID`)
    REFERENCES `RegisteredUsers` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Branch` ;

CREATE TABLE IF NOT EXISTS `Branch` (
  `branchID` INT NOT NULL,
  `branchName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`branchID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeneralUser_canBrowse_Catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeneralUser_canBrowse_Catalog` ;

CREATE TABLE IF NOT EXISTS `GeneralUser_canBrowse_Catalog` (
  `GeneralUser_Type` VARCHAR(45) NOT NULL,
  `Catalog_catalogID` INT NOT NULL,
  PRIMARY KEY (`GeneralUser_Type`, `Catalog_catalogID`),
  INDEX `fk_GeneralUser_has_Catalog_Catalog1_idx` (`Catalog_catalogID` ASC) VISIBLE,
  INDEX `fk_GeneralUser_has_Catalog_GeneralUser1_idx` (`GeneralUser_Type` ASC) VISIBLE,
  CONSTRAINT `fk_GeneralUser_has_Catalog_GeneralUser1`
    FOREIGN KEY (`GeneralUser_Type`)
    REFERENCES `GeneralUser` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GeneralUser_has_Catalog_Catalog1`
    FOREIGN KEY (`Catalog_catalogID`)
    REFERENCES `Catalog` (`catalogID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book` ;

CREATE TABLE IF NOT EXISTS `Book` (
  `ISBN` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Author` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  `Availability` INT NULL,
  `Description` VARCHAR(45) NULL,
  `PublishedDate` DATE NULL,
  PRIMARY KEY (`ISBN`, `Title`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Staff` ;

CREATE TABLE IF NOT EXISTS `Staff` (
  `EmployeeID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EmployeeID`, `Name`, `Type`),
  INDEX `Type_idx` (`Type` ASC) VISIBLE,
  CONSTRAINT `Type`
    FOREIGN KEY (`Type`)
    REFERENCES `GeneralUser` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `EmployeeID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Branch` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`, `Branch`),
  INDEX `ManagerBranch_idx` (`Branch` ASC) VISIBLE,
  CONSTRAINT `ManagerBranch`
    FOREIGN KEY (`Branch`)
    REFERENCES `Branch` (`branchID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ManagerID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `Staff` (`EmployeeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employees` ;

CREATE TABLE IF NOT EXISTS `Employees` (
  `EmployeeID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `BranchID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`, `Name`, `BranchID`),
  INDEX `EmployeeBranch_idx` (`BranchID` ASC) VISIBLE,
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `Staff` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EmployeeBranch`
    FOREIGN KEY (`BranchID`)
    REFERENCES `Branch` (`branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
