-- MySQL Script generated by MySQL Workbench
-- Sun May 21 22:04:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE librarymanagementdb;
-- -----------------------------------------------------
-- Table `GeneralUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeneralUser` ;

CREATE TABLE IF NOT EXISTS `GeneralUser` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `role` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RegisteredUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RegisteredUser` ;

CREATE TABLE IF NOT EXISTS `RegisteredUser` (
  `registeredUserID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`registeredUserID`),
  CONSTRAINT `registeredUserID`
    FOREIGN KEY (`registeredUserID`)
    REFERENCES `GeneralUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryStaff` ;

CREATE TABLE IF NOT EXISTS `LibraryStaff` (
  `libraryStaffID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`libraryStaffID`),
  CONSTRAINT `libraryStaffID`
    FOREIGN KEY (`libraryStaffID`)
    REFERENCES `GeneralUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Organization` ;

CREATE TABLE IF NOT EXISTS `Organization` (
  `organizationID` INT NOT NULL AUTO_INCREMENT,
  `organization` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`organizationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBranch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryBranch` ;

CREATE TABLE IF NOT EXISTS `LibraryBranch` (
  `branchID` INT NOT NULL AUTO_INCREMENT,
  `branchName` VARCHAR(45) NOT NULL,
  `organization` INT NOT NULL,
  PRIMARY KEY (`branchID`),
  INDEX `organization_idx` (`organization` ASC) VISIBLE,
  CONSTRAINT `organization`
    FOREIGN KEY (`organization`)
    REFERENCES `Organization` (`organizationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `branch` INT NOT NULL,
  `role` INT NOT NULL,
  `isManager` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`employeeID`),
  INDEX `role_idx` (`role` ASC) VISIBLE,
  INDEX `branch_idx` (`branch` ASC) VISIBLE,
  INDEX `manager_index` (`isManager` ASC) VISIBLE,
  CONSTRAINT `employeeID`
    FOREIGN KEY (`employeeID`)
    REFERENCES `LibraryStaff` (`libraryStaffID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `employeeRole`
    FOREIGN KEY (`role`)
    REFERENCES `Role` (`role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `employeeBranch`
    FOREIGN KEY (`branch`)
    REFERENCES `LibraryBranch` (`branchID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `employeeID` INT NOT NULL,
  `managerID` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`employeeID`),
  INDEX `managerID_idx` (`managerID` ASC) VISIBLE,
  CONSTRAINT `managerEmployeeID`
    FOREIGN KEY (`employeeID`)
    REFERENCES `Employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `managerID`
    FOREIGN KEY (`managerID`)
    REFERENCES `Employee` (`isManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libraryCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libraryCard` ;

CREATE TABLE IF NOT EXISTS `libraryCard` (
  `cardID` INT NOT NULL,
  `expiry` INT NOT NULL,
  PRIMARY KEY (`cardID`),
  UNIQUE INDEX `cardID_UNIQUE` (`cardID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userAccount` ;

CREATE TABLE IF NOT EXISTS `userAccount` (
  `accountID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `libraryCard` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`accountID`),
  INDEX `accountRole_idx` (`role` ASC) VISIBLE,
  INDEX `accountCard_idx` (`libraryCard` ASC) VISIBLE,
  CONSTRAINT `accountRole`
    FOREIGN KEY (`role`)
    REFERENCES `Role` (`role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `accountCard`
    FOREIGN KEY (`libraryCard`)
    REFERENCES `libraryCard` (`cardID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `accountID`
    FOREIGN KEY (`accountID`)
    REFERENCES `RegisteredUser` (`registeredUserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contentType` ;

CREATE TABLE IF NOT EXISTS `contentType` (
  `contentTypeID` INT NOT NULL AUTO_INCREMENT,
  `contentType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`contentTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Catalog` ;

CREATE TABLE IF NOT EXISTS `Catalog` (
  `catalogID` INT NOT NULL AUTO_INCREMENT,
  `catalogType` INT NOT NULL,
  PRIMARY KEY (`catalogID`),
  INDEX `catalogType_idx` (`catalogType` ASC) VISIBLE,
  CONSTRAINT `catalogType`
    FOREIGN KEY (`catalogType`)
    REFERENCES `contentType` (`contentTypeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Actions` ;

CREATE TABLE IF NOT EXISTS `Actions` (
  `actionID` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  `catalog` INT NOT NULL,
  PRIMARY KEY (`actionID`),
  INDEX `role_idx` (`role` ASC) VISIBLE,
  INDEX `catalogID_idx` (`catalog` ASC) VISIBLE,
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `Role` (`role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `catalogID`
    FOREIGN KEY (`catalog`)
    REFERENCES `Catalog` (`catalogType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `studentID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`studentID`),
  CONSTRAINT `studentID`
    FOREIGN KEY (`studentID`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Faculty` ;

CREATE TABLE IF NOT EXISTS `Faculty` (
  `facultyID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`facultyID`),
  CONSTRAINT `facultyID`
    FOREIGN KEY (`facultyID`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PaymentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PaymentType` ;

CREATE TABLE IF NOT EXISTS `PaymentType` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zipcode` CHAR(5) NOT NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BillingInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BillingInfo` ;

CREATE TABLE IF NOT EXISTS `BillingInfo` (
  `billingID` INT NOT NULL AUTO_INCREMENT,
  `userBill` INT NOT NULL,
  `paymentType` INT NOT NULL,
  `amount` DECIMAL(6,2) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`billingID`),
  INDEX `userBill_idx` (`userBill` ASC) VISIBLE,
  INDEX `paymentTypeID_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `userBill`
    FOREIGN KEY (`userBill`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `paymentTypeID`
    FOREIGN KEY (`paymentType`)
    REFERENCES `PaymentType` (`typeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CreditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CreditCard` ;

CREATE TABLE IF NOT EXISTS `CreditCard` (
  `cardNumber` INT NOT NULL,
  `paymentType` INT NOT NULL,
  `expiry` DATE NOT NULL,
  `cvv` CHAR(3) NOT NULL,
  PRIMARY KEY (`cardNumber`, `paymentType`),
  INDEX `fk_Credit Card_PaymentType1_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `fk_Credit Card_PaymentType1`
    FOREIGN KEY (`paymentType`)
    REFERENCES `PaymentType` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DebitCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DebitCard` ;

CREATE TABLE IF NOT EXISTS `DebitCard` (
  `cardNumber` INT NOT NULL,
  `paymentType` INT NOT NULL,
  `expiry` DATE NOT NULL,
  `cvv` CHAR(3) NOT NULL,
  PRIMARY KEY (`cardNumber`, `paymentType`),
  INDEX `fk_Credit Card_PaymentType1_idx` (`paymentType` ASC) VISIBLE,
  CONSTRAINT `paymentTypeDebit`
    FOREIGN KEY (`paymentType`)
    REFERENCES `PaymentType` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MailingList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MailingList` ;

CREATE TABLE IF NOT EXISTS `MailingList` (
  `mailingListID` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  PRIMARY KEY (`mailingListID`),
  INDEX `mailingListUser_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `mailingListUser`
    FOREIGN KEY (`user`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Publisher` ;

CREATE TABLE IF NOT EXISTS `Publisher` (
  `publisherID` INT NOT NULL AUTO_INCREMENT,
  `publisherName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`publisherID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Entries` ;

CREATE TABLE IF NOT EXISTS `Entries` (
  `entryID` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `publisher` INT NOT NULL,
  PRIMARY KEY (`entryID`),
  UNIQUE INDEX `entryID_UNIQUE` (`entryID` ASC) VISIBLE,
  INDEX `publisherID_idx` (`publisher` ASC) VISIBLE,
  CONSTRAINT `entryID`
    FOREIGN KEY (`entryID`)
    REFERENCES `Catalog` (`catalogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `publisherID`
    FOREIGN KEY (`publisher`)
    REFERENCES `Publisher` (`publisherID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Genre` ;

CREATE TABLE IF NOT EXISTS `Genre` (
  `genreID` INT NOT NULL AUTO_INCREMENT,
  `genreType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Books` ;

CREATE TABLE IF NOT EXISTS `Books` (
  `ISBN` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `availability` INT NOT NULL,
  `genre` INT NOT NULL,
  `releasedYear` INT NOT NULL,
  `genre2` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  INDEX `bookGenre_idx` (`genre` ASC) VISIBLE,
  INDEX `secondGenre_idx` (`genre2` ASC) VISIBLE,
  CONSTRAINT `ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bookGenre`
    FOREIGN KEY (`genre`)
    REFERENCES `Genre` (`genreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `secondGenre`
    FOREIGN KEY (`genre2`)
    REFERENCES `Genre` (`genreID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultimediaContent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultimediaContent` ;

CREATE TABLE IF NOT EXISTS `MultimediaContent` (
  `multimediaContentID` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `multimediaPublisher` INT NOT NULL,
  PRIMARY KEY (`multimediaContentID`),
  INDEX `multimediaPublisher_idx` (`multimediaPublisher` ASC) VISIBLE,
  CONSTRAINT `multimediaContentID`
    FOREIGN KEY (`multimediaContentID`)
    REFERENCES `Catalog` (`catalogID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `multimediaPublisher`
    FOREIGN KEY (`multimediaPublisher`)
    REFERENCES `Publisher` (`publisherID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EBooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EBooks` ;

CREATE TABLE IF NOT EXISTS `EBooks` (
  `ISBNEbook` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `genre` INT NOT NULL,
  `description` VARCHAR(2048) NOT NULL,
  `releasedYear` INT NOT NULL,
  `secondGenre` INT NOT NULL,
  PRIMARY KEY (`ISBNEbook`),
  UNIQUE INDEX `ISBNEbook_UNIQUE` (`ISBNEbook` ASC) VISIBLE,
  INDEX `ebookGenre_idx` (`genre` ASC) VISIBLE,
  INDEX `secondEbookGenre_idx` (`secondGenre` ASC) VISIBLE,
  CONSTRAINT `ISBNEbook`
    FOREIGN KEY (`ISBNEbook`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ebookGenre`
    FOREIGN KEY (`genre`)
    REFERENCES `Genre` (`genreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `secondEbookGenre`
    FOREIGN KEY (`secondGenre`)
    REFERENCES `Genre` (`genreID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thesaurus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Thesaurus` ;

CREATE TABLE IF NOT EXISTS `Thesaurus` (
  `thesaurusISBN` INT NOT NULL,
  `releasedYear` INT NOT NULL,
  PRIMARY KEY (`thesaurusISBN`),
  UNIQUE INDEX `thesaurusISBN_UNIQUE` (`thesaurusISBN` ASC) VISIBLE,
  CONSTRAINT `thesaurusISBN`
    FOREIGN KEY (`thesaurusISBN`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Encyclopedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Encyclopedia` ;

CREATE TABLE IF NOT EXISTS `Encyclopedia` (
  `encyclopediaISBN` INT NOT NULL,
  `releasedYear` INT NOT NULL,
  PRIMARY KEY (`encyclopediaISBN`),
  UNIQUE INDEX `encyclopediaISBN_UNIQUE` (`encyclopediaISBN` ASC) VISIBLE,
  CONSTRAINT `encyclopediaISBN`
    FOREIGN KEY (`encyclopediaISBN`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Magazine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Magazine` ;

CREATE TABLE IF NOT EXISTS `Magazine` (
  `magazineID` INT NOT NULL AUTO_INCREMENT,
  `releasedYear` INT NOT NULL,
  PRIMARY KEY (`magazineID`),
  CONSTRAINT `magazineID`
    FOREIGN KEY (`magazineID`)
    REFERENCES `Entries` (`entryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Holds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Holds` ;

CREATE TABLE IF NOT EXISTS `Holds` (
  `holdID` INT NOT NULL AUTO_INCREMENT,
  `userHold` INT NOT NULL,
  `bookReservation` INT NOT NULL,
  PRIMARY KEY (`holdID`),
  INDEX `userHold_idx` (`userHold` ASC) VISIBLE,
  INDEX `bookHold_idx` (`bookReservation` ASC) VISIBLE,
  CONSTRAINT `userHold`
    FOREIGN KEY (`userHold`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bookHold`
    FOREIGN KEY (`bookReservation`)
    REFERENCES `Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Music` ;

CREATE TABLE IF NOT EXISTS `Music` (
  `musicID` INT NOT NULL AUTO_INCREMENT,
  `artist` VARCHAR(45) NOT NULL,
  `releasedYear` INT NOT NULL,
  PRIMARY KEY (`musicID`),
  UNIQUE INDEX `musicID_UNIQUE` (`musicID` ASC) VISIBLE,
  CONSTRAINT `musicID`
    FOREIGN KEY (`musicID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Videos` ;

CREATE TABLE IF NOT EXISTS `Videos` (
  `videoID` INT NOT NULL AUTO_INCREMENT,
  `releasedYear` INT NOT NULL,
  PRIMARY KEY (`videoID`),
  UNIQUE INDEX `videoID_UNIQUE` (`videoID` ASC) VISIBLE,
  CONSTRAINT `videoID`
    FOREIGN KEY (`videoID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ResearchPaper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResearchPaper` ;

CREATE TABLE IF NOT EXISTS `ResearchPaper` (
  `PMID` INT NOT NULL,
  `abstract` VARCHAR(2048) NOT NULL,
  `releasedYear` INT NOT NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`PMID`),
  UNIQUE INDEX `DOI_UNIQUE` (`PMID` ASC) VISIBLE,
  INDEX `researchPaperAuthor_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `PMID`
    FOREIGN KEY (`PMID`)
    REFERENCES `MultimediaContent` (`multimediaContentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `researchPaperAuthor`
    FOREIGN KEY (`author`)
    REFERENCES `RegisteredUser` (`registeredUserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borrows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borrows` ;

CREATE TABLE IF NOT EXISTS `Borrows` (
  `borrowID` INT NOT NULL AUTO_INCREMENT,
  `userIDBorrowed` INT NOT NULL,
  `bookBorrowed` INT NOT NULL,
  `returned` BIT NOT NULL DEFAULT b'0',
  `borrowedBranch` INT NOT NULL,
  PRIMARY KEY (`borrowID`),
  INDEX `userIDBorrowed_idx` (`userIDBorrowed` ASC) VISIBLE,
  INDEX `bookBorrowed_idx` (`bookBorrowed` ASC) VISIBLE,
  INDEX `branchBorrowed_idx` (`borrowedBranch` ASC) VISIBLE,
  CONSTRAINT `userIDBorrowed`
    FOREIGN KEY (`userIDBorrowed`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bookBorrowed`
    FOREIGN KEY (`bookBorrowed`)
    REFERENCES `Books` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `branchBorrowed`
    FOREIGN KEY (`borrowedBranch`)
    REFERENCES `LibraryBranch` (`branchID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patron`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patron` ;

CREATE TABLE IF NOT EXISTS `Patron` (
  `patronID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`patronID`),
  UNIQUE INDEX `patronID_UNIQUE` (`patronID` ASC) VISIBLE,
  CONSTRAINT `patronUserID`
    FOREIGN KEY (`patronID`)
    REFERENCES `userAccount` (`accountID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Watched`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Watched` ;

CREATE TABLE IF NOT EXISTS `Watched` (
  `watchID` INT NOT NULL AUTO_INCREMENT,
  `userIDWatched` INT NOT NULL,
  `videoWatched` INT NOT NULL,
  `videoCredits` INT NOT NULL,
  PRIMARY KEY (`watchID`),
  INDEX `userWatched_idx` (`userIDWatched` ASC) VISIBLE,
  INDEX `videoWatched_idx` (`videoWatched` ASC) VISIBLE,
  INDEX `videoCredits_idx` (`videoCredits` ASC) VISIBLE,
  CONSTRAINT `userWatched`
    FOREIGN KEY (`userIDWatched`)
    REFERENCES `RegisteredUser` (`registeredUserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `videoWatched`
    FOREIGN KEY (`videoWatched`)
    REFERENCES `Videos` (`videoID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `videoCredits`
    FOREIGN KEY (`videoCredits`)
    REFERENCES `Publisher` (`publisherID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
